<?php
define("DB_HOSTNAME",'XXXXXXXXXXXXX');
define("DB_USERNAME",'XXXXXXXXXXXXX');
define("DB_PASSWORD",'XXXXXXXXXXXXX');
define("DB_DATABASE",'XXXXXXXXXXXXX');

define("GITHUB_WEBHOOK_SECRET",'XXXXXXXXXXXXX')
